project:
  type: website
  output-dir: docs

website:
  title: "Edwin's Site"
  navbar:
    left:
      - text: "About"
        href: about.qmd
      - projects.qmd
      - cv.qmd
      - contact.qmd
  page-footer:
    center: "Â© 2025 Edwin Leck. All rights reserved."

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
