project:
  type: website
  output-dir: docs

website:
  navbar:
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/edwinleck/
        aria-label: LinkedIn
      - icon: github
        menu:
          - text: Source Code
            href: https://code.com
          - text: GitHub Account
            href: https://github.com/edwinleck
        aria-label: GitHub
      - icon: envelope
        href: mailto:edwinleck@gmail.com
        aria-label: Email
  page-footer:
    center: "Â© 2025 Edwin Leck. All rights reserved."

format:
  html:
    css: styles.css
    theme:
      light: flatly
      dark: darkly
    toc: true
